### PR TITLE
Update `ember-cli` and dependencies

### PR DESCRIPTION
**Pull request by btecu**

### CODE REVIEW

**Comment by btecu** [comment]
@ttill I think we need to:
1. Update `ember-cli` to latest version
2. Fix lint & deprecations

I took a stab at this in #152 and I got it updated and fixed a few deprecations, but there are several left. Do you have some cycles to help?

**Comment by lrdiv** [comment]
I'm attempting to pick this up and update tests, but I'm spinning my wheels trying to rewrite this block using the new test APIs https://github.com/adopted-ember-addons/ember-notify/blob/master/tests/unit/components/ember-notify-test.js#L16-L21

**Comment by btecu** [comment]
@lrdiv is the rendering test not covered by those tests using `testLevelMethod`?

**Comment by lrdiv** [comment]
> @lrdiv is the rendering test not covered by those tests using `testLevelMethod`?
> Thanks for picking this up!

I'm not really sure. It's confusing that the tests in `tests/unit/components` are currently like hybrid unit-integration tests where they seem to depend on rendering, but also want to access the instance being tested. Maybe I'm just not understanding because I haven't seen unit tests like this before

**Comment by btecu** [comment]
This project was started a long time ago (January 2014) so a lot of things have evolved in Ember but it's possible that the project did not keep up with all the updates.

**Pull request merged**
